### ISSUE TITLE
can't access https://www.facebook.com

### ISSUE THREAD

**Issue by ncisoft** [greensea/obfstunnel#2]
the command line is: -m random,salt=google,padlen=36,maxlen=1400

I can get result via:
 curl -Lv --socks5 127.0.0.1:10800 https://www.google.com

but can't get result via:
 curl -Lv --socks5 127.0.0.1:10800 https://www.facebook.com

could you please help me?

**Comment by greensea** [comment]
Does curl reports any error?
2015年11月6日 下午3:18，"ncisoft" <notifications@github.com>写道：

**Comment by ncisoft** [comment]
sorry for my mistake, I used wrong curl parameters with --socks5, once I changed to --socks5-hostname, it works fine.

**Comment by ncisoft** [comment]
sorry for my mistake, I used wrong curl parameters with --socks5, once I changed to --socks5-hostname, it works fine.
